version: '2'
services: 
  app:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - ".:/code"
    depends_on:
      - iis-sandbox
      - v2-to-fhir
    links:
      - iis-sandbox
      - v2-to-fhir
  iis-sandbox:
    build: ./IIS-Sandbox
    ports:
      - "8081:8080"
    environment:
      IIS_SANDBOX_USERNAME: mitre
      IIS_SANDBOX_PASSWORD: mitre
      IIS_SANDBOX_FACILITY_ID: MITRE Healthcare
      IIS_SANDBOX_HOST: http://localhost:8081
  v2-to-fhir: 
    build: ./hl7v2-fhir-vaccine-credential-converter
    environment:
      V2_TO_FHIR_HOST: http://localhost:3000
    ports:
      - "3000:3000"
