version: '3'
services: 
  app:
    build: .
    ports:
      - "5000:5000"
    command: bundle exec rails s -p 5000
    depends_on:
      - iis-sandbox
      - v2-to-fhir
    links:
      - iis-sandbox
      - v2-to-fhir
  iis-sandbox:
    build: ./IIS-Sandbox
    environment:
      IIS_SANDBOX_USERNAME: mitre
      IIS_SANDBOX_PASSWORD: mitre
      IIS_SANDBOX_FACILITY_ID: MITRE Healthcare
      IIS_SANDBOX_HOST: http://localhost:8081
  v2-to-fhir: 
    build: ./hl7v2-fhir-vaccine-credential-converter
    environment:
      V2_TO_FHIR_HOST: http://localhost:3000
    ports:
      - "3000:3000"
